name: lumio_example
description: A simple example of Lumio usage
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  lumio:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
